package com.example.springbootproject01.mapper;

import com.example.springbootproject01.bean.GoodsColor;
import com.example.springbootproject01.bean.GoodsColorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsColorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int countByExample(GoodsColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int deleteByExample(GoodsColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int insert(GoodsColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int insertSelective(GoodsColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    List<GoodsColor> selectByExample(GoodsColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    GoodsColor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int updateByExampleSelective(@Param("record") GoodsColor record, @Param("example") GoodsColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int updateByExample(@Param("record") GoodsColor record, @Param("example") GoodsColorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int updateByPrimaryKeySelective(GoodsColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int updateByPrimaryKey(GoodsColor record);
}