package com.example.springbootproject01.mapper;

import com.example.springbootproject01.bean.GoodsConfig;
import com.example.springbootproject01.bean.GoodsConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int countByExample(GoodsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int deleteByExample(GoodsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int insert(GoodsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int insertSelective(GoodsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    List<GoodsConfig> selectByExample(GoodsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    GoodsConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int updateByExampleSelective(@Param("record") GoodsConfig record, @Param("example") GoodsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int updateByExample(@Param("record") GoodsConfig record, @Param("example") GoodsConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int updateByPrimaryKeySelective(GoodsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_config
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    int updateByPrimaryKey(GoodsConfig record);
}