package com.example.springbootproject01.bean;

import lombok.Data;

@Data
public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.user_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.consignee
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.region
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.detail_address
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.label
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.user_id
     *
     * @return the value of address.user_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.user_id
     *
     * @param userId the value for address.user_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.consignee
     *
     * @return the value of address.consignee
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.consignee
     *
     * @param consignee the value for address.consignee
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.region
     *
     * @return the value of address.region
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.region
     *
     * @param region the value for address.region
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detail_address
     *
     * @return the value of address.detail_address
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detail_address
     *
     * @param detailAddress the value for address.detail_address
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.label
     *
     * @return the value of address.label
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.label
     *
     * @param label the value for address.label
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }
}