package com.example.springbootproject01.bean;

import lombok.Data;

import java.math.BigDecimal;
@Data
public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.message
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.classify
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String classify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.index_img
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String indexImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.detail_img
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String detailImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.message
     *
     * @return the value of goods.message
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.message
     *
     * @param message the value for goods.message
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.classify
     *
     * @return the value of goods.classify
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.classify
     *
     * @param classify the value for goods.classify
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setClassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.index_img
     *
     * @return the value of goods.index_img
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getIndexImg() {
        return indexImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.index_img
     *
     * @param indexImg the value for goods.index_img
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setIndexImg(String indexImg) {
        this.indexImg = indexImg == null ? null : indexImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.detail_img
     *
     * @return the value of goods.detail_img
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getDetailImg() {
        return detailImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.detail_img
     *
     * @param detailImg the value for goods.detail_img
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setDetailImg(String detailImg) {
        this.detailImg = detailImg == null ? null : detailImg.trim();
    }
}