package com.example.springbootproject01.bean;

public class GoodsColor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_color.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_color.goods_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_color.color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String color;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_color.id
     *
     * @return the value of goods_color.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_color.id
     *
     * @param id the value for goods_color.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_color.goods_id
     *
     * @return the value of goods_color.goods_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_color.goods_id
     *
     * @param goodsId the value for goods_color.goods_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_color.color
     *
     * @return the value of goods_color.color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_color.color
     *
     * @param color the value for goods_color.color
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }
}