package com.example.springbootproject01.bean;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
@Data
public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.consignee
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.address
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.creation_time
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date creationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.consignee
     *
     * @return the value of order.consignee
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.consignee
     *
     * @param consignee the value for order.consignee
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.address
     *
     * @return the value of order.address
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.address
     *
     * @param address the value for order.address
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.creation_time
     *
     * @return the value of order.creation_time
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.creation_time
     *
     * @param creationTime the value for order.creation_time
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
}