package com.example.springbootproject01.bean;

import lombok.Data;

@Data
public class Orderdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.order_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.goods_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.goods_num
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private Integer goodsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.note
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.id
     *
     * @return the value of orderdetail.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.id
     *
     * @param id the value for orderdetail.id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.order_id
     *
     * @return the value of orderdetail.order_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.order_id
     *
     * @param orderId the value for orderdetail.order_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.goods_id
     *
     * @return the value of orderdetail.goods_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.goods_id
     *
     * @param goodsId the value for orderdetail.goods_id
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.goods_num
     *
     * @return the value of orderdetail.goods_num
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.goods_num
     *
     * @param goodsNum the value for orderdetail.goods_num
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.note
     *
     * @return the value of orderdetail.note
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.note
     *
     * @param note the value for orderdetail.note
     *
     * @mbggenerated Sat Jun 18 08:39:01 CST 2022
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}